### ISSUE TITLE
Separate program into smaller functions

### ISSUE THREAD

**Issue by TimJentzsch** [erenbektas/ultimate-text-analyzer#3]
To facilitate reuse of the functionality, it is a good idea to move each feature into a separate function. Then we can use them in different contexts, e.g. if we want to display the output in different ways.

In this case, each function could take the text as input and return the stats, for example one function would get the text as input and return the word count. The main program can then use the different functions to assemble the output text.

**Comment by erenbektas** [comment]
Done!
